// ==UserScript==
// @name         Capitritus
// @namespace    capitritus
// @version      3.2.0
// @description  Assistente de estudo com IA, análise automática e destaque visual de recomendações.
// @author       israelmarques1024-dotcom
// @match        *://*/*
// @grant        GM_registerMenuCommand
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_xmlhttpRequest
// @connect      automatic-palm-tree-r49v55xwgr59f57p4-8000.app.github.dev
// @updateURL    https://raw.githubusercontent.com/israelmarques1024-dotcom/Israelmarques1024-dotcom/main/studydb/capitritus.user.js
// @downloadURL  https://raw.githubusercontent.com/israelmarques1024-dotcom/Israelmarques1024-dotcom/main/studydb/capitritus.user.js
// @run-at       document-idle
// ==/UserScript==

(()=>{'use strict';
const V='3.2.0';
const API_KEY='capitritus_api_url_v1';
const API_DEFAULT='https://automatic-palm-tree-r49v55xwgr59f57p4-8000.app.github.dev';
const S={items:[],busy:false,pending:false,timer:0,online:null,status:'Inicializando…',cache:new Map(),lastScroll:''};
const api=()=>String(GM_getValue(API_KEY,API_DEFAULT)||API_DEFAULT).replace(/\/+$/,'');
const q=(r,s)=>{try{return[...r.querySelectorAll(s)]}catch{return[]}};
const text=e=>String(e?.innerText||e?.textContent||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const norm=s=>String(s||'').normalize('NFKC').toLocaleLowerCase('pt-BR').replace(/[“”"'`´]/g,'').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const vis=e=>{if(!e||!(e instanceof Element))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};
const platform=()=>/saladofuturo|educacao\.sp\.gov\.br|cmsp/i.test(location.hostname)?'Sala do Futuro/CMSP':location.hostname;
const label=e=>{if(e?.id)try{const l=document.querySelector(`label[for="${CSS.escape(e.id)}"]`);if(l)return l}catch{}return e?.closest?.('label,[role="radio"],[role="option"],[class*="option" i],[class*="choice" i]')||e?.parentElement||e};
const optText=e=>text(e?.matches?.('input')?label(e):e)||e?.getAttribute?.('aria-label')||e?.value||'';

function root(e){let p=e;while(p&&p!==document.body){const t=text(p);if(/Quest[aã]o\s*\d+\s*de\s*\d+/i.test(t)&&t.length<18000)return p;p=p.parentElement}return e?.closest?.('[class*="question" i],[id*="question" i],fieldset,form,[role="group"]')||e?.parentElement?.parentElement||e?.parentElement}
function stem(r,opts=[]){let t=text(r).replace(/Quest[aã]o\s*\d+\s*de\s*\d+/ig,' ').replace(/\b\d+\s*PONTOS?\b/ig,' ').replace(/\bCerto\s*Errado\b/ig,' ');for(const o of opts){const i=t.indexOf(o.text);if(i>=0)t=t.slice(0,i)+t.slice(i+o.text.length)}return t.replace(/\s+/g,' ').trim().slice(0,6000)}
function radioGroups(){const m=new Map();for(const e of q(document,'input[type="radio"],input[type="checkbox"]')){if(!vis(e)&&!vis(label(e)))continue;const r=root(e),k=e.name||('anon-'+(r?.dataset?.capid||(r&&(r.dataset.capid=Math.random().toString(36).slice(2)))));if(!m.has(k))m.set(k,[]);m.get(k).push(e)}const out=[...m.values()].filter(g=>g.length>=2&&g.length<=30);for(const rg of q(document,'[role="radiogroup"]')){const g=q(rg,'[role="radio"]').filter(vis);if(g.length>=2)out.push(g)}return out}
function choices(){const out=[],seen=new Set();for(const g of radioGroups()){const opts=g.map(e=>({element:e,visual:label(e),text:optText(e)})).filter(o=>o.text);if(opts.length<2)continue;let r=root(g[0]);const labs=opts.map(o=>norm(o.text)),tf=opts.length===2&&labs.some(x=>/certo|verdadeiro/.test(x))&&labs.some(x=>/errado|falso/.test(x));if(tf){let p=g[0].parentElement,b=r;for(let i=0;i<6&&p;i++,p=p.parentElement){const rs=q(p,'input[type="radio"],[role="radio"]');if(rs.length===2&&text(p).length<2500)b=p;if(rs.length>2)break}r=b}const question=stem(r,opts),sig=norm(question)+'|'+opts.map(o=>norm(o.text)).join('|');if(question.length<8||seen.has(sig))continue;seen.add(sig);out.push({type:tf?'truefalse':'choice',question,options:opts,root:r,platform:platform()})}return out}
function fills(){const out=[],m=new Map(),controls=[...q(document,'select').filter(vis),...q(document,'[role="combobox"],[aria-haspopup="listbox"]').filter(vis)];for(const c of controls){const r=root(c);if(!r)continue;if(!m.has(r))m.set(r,[]);m.get(r).push(c)}for(const[r,cs]of m){const question=stem(r,[]);cs.forEach((c,i)=>{let opts=[];if(c.matches('select'))opts=[...c.options].map(o=>({text:text(o),element:o,visual:c})).filter(o=>o.text&&!/selecione|escolha|--/i.test(o.text));else{const ids=[c.getAttribute('aria-controls'),c.getAttribute('aria-owns')].filter(Boolean),sc=[...ids.map(x=>document.getElementById(x)).filter(Boolean),r],els=[];for(const s of sc)els.push(...q(s,'[role="option"],[data-value],[data-label]'));const seen=new Set();opts=els.map(e=>({text:text(e)||e.getAttribute('aria-label')||'',element:e,visual:c})).filter(o=>o.text&&!seen.has(norm(o.text))&&seen.add(norm(o.text)))}out.push({type:'fill',question:`${question} [lacuna ${i+1} de ${cs.length}]`,options:opts,control:c,root:r,platform:platform()})})}return out}
function opens(){const out=[],seen=new Set();for(const c of [...q(document,'textarea').filter(vis),...q(document,'[contenteditable="true"]').filter(vis)]){const r=root(c),question=stem(r,[]);if(question.length<15||seen.has(norm(question)))continue;seen.add(norm(question));out.push({type:'open',question,control:c,root:r,platform:platform()})}return out}

function request(method,url,body){return new Promise((ok,no)=>GM_xmlhttpRequest({method,url,headers:body?{'Content-Type':'application/json'}:{},data:body?JSON.stringify(body):undefined,timeout:180000,onload:r=>{if(r.status<200||r.status>=300)return no(Error(`HTTP ${r.status}`));try{ok(JSON.parse(r.responseText))}catch{no(Error('JSON inválido'))}},onerror:()=>no(Error('falha de rede')),ontimeout:()=>no(Error('timeout'))}))}
function kind(it){return it.type==='choice'?'multiple_choice':it.type==='truefalse'?'true_false':it.type==='fill'?'fill_blank':'open_response'}
async function solve(it){const key=norm(it.question)+'|'+(it.options||[]).map(o=>norm(o.text)).join('|');if(S.cache.has(key))return S.cache.get(key);const d=await request('POST',api()+'/solve',{kind:kind(it),question:it.question,options:(it.options||[]).map(o=>o.text),context:`${platform()} | ${document.title||''}`.slice(0,1000)});let r=null;if(it.type==='open'){r={hints:Array.isArray(d.hints)?d.hints.map(String).filter(Boolean).slice(0,4):[],confidence:+d.confidence||0,explanation:d.explanation||''}}else{let idx=Number.isInteger(d.answer_index)?d.answer_index:null;if(idx===null&&d.answer&&it.options?.length){const a=norm(d.answer);idx=it.options.findIndex(o=>norm(o.text)===a);if(idx<0)idx=it.options.findIndex(o=>a.includes(norm(o.text))||norm(o.text).includes(a))}const confidence=Math.max(0,Math.min(1,+d.confidence||0));if(idx!==null&&idx>=0&&idx<(it.options?.length||0))r={index:idx,answer:it.options[idx].text,confidence,explanation:d.explanation||''};else if(it.type==='fill'&&d.answer)r={answer:String(d.answer),confidence,explanation:d.explanation||''}}S.cache.set(key,r);return r}

function clear(){q(document,'.cap-mark').forEach(e=>e.classList.remove('cap-mark'));q(document,'.cap-badge,.cap-inline-hint').forEach(e=>e.remove())}
function addBadge(v,s){if(!v||v.querySelector?.('.cap-badge'))return;const b=document.createElement('span');b.className='cap-badge';b.textContent=`Capitritus recomenda · ${Math.round((s.confidence||0)*100)}%`;v.appendChild(b)}
function addInlineHint(it,s){const c=it.control;if(!c||!c.parentElement)return;if(c.parentElement.querySelector('.cap-inline-hint'))return;const h=document.createElement('div');h.className='cap-inline-hint';h.innerHTML=`<b>Sugestão da IA:</b> ${esc(s.answer||'')}<span>${Math.round((s.confidence||0)*100)}%</span>`;c.insertAdjacentElement('afterend',h)}
function mark(it){const s=it.suggestion;if(!s)return;if(it.type==='fill'){it.control?.classList.add('cap-mark');addInlineHint(it,s);return}if(!Number.isInteger(s.index)||s.confidence<.25)return;const v=it.options?.[s.index]?.visual;if(!v)return;v.classList.add('cap-mark');addBadge(v,s)}
function firstRecommended(){for(const it of S.items){if(it.type==='fill'&&it.suggestion?.answer)return it.control||it.root;if(Number.isInteger(it.suggestion?.index))return it.options?.[it.suggestion.index]?.visual||it.root}return null}
function scrollToRecommendation(){const e=firstRecommended();if(!e)return;const key=norm(text(root(e))).slice(0,180);if(key&&key===S.lastScroll)return;S.lastScroll=key;try{e.scrollIntoView({behavior:'smooth',block:'center'})}catch{e.scrollIntoView()}setTimeout(()=>e.classList?.add('cap-attention'),500);setTimeout(()=>e.classList?.remove('cap-attention'),2500)}

async function health(){try{const h=await request('GET',api()+'/health');S.online=!!h.ok;S.status=h.ok?`IA online · ${h.model||'Qwen'}`:'Modelo ainda não está pronto'}catch(e){S.online=false;S.status=`IA offline · ${e.message}`}render()}
async function analyze(){if(S.busy){S.pending=true;return}S.busy=true;S.pending=false;try{S.items=[...choices(),...fills(),...opens()];clear();S.status=`Consultando IA · 0/${S.items.length}`;render();for(let i=0;i<S.items.length;i++){const it=S.items[i];try{const r=await solve(it);S.online=true;if(it.type==='open'){it.hints=r?.hints||[];it.explanation=r?.explanation||''}else it.suggestion=r}catch(e){S.online=false}S.status=`Consultando IA · ${i+1}/${S.items.length}`;clear();S.items.forEach(mark);render()}S.status=S.online===false?'IA offline':`IA online · ${S.items.length} item(ns) analisado(s)`;clear();S.items.forEach(mark);render();scrollToRecommendation()}finally{S.busy=false;if(S.pending){S.pending=false;clearTimeout(S.timer);S.timer=setTimeout(analyze,700)}}}

function style(){if(document.getElementById('cap-style'))return;const s=document.createElement('style');s.id='cap-style';s.textContent=`
.cap-mark{outline:4px solid #ffd54a!important;outline-offset:4px!important;box-shadow:0 0 0 8px #ffd54a33,0 0 28px #ffd54a55!important;border-radius:10px!important;position:relative!important}
.cap-badge{display:inline-flex!important;align-items:center!important;margin-left:8px!important;padding:4px 9px!important;border-radius:999px!important;background:#ffd54a!important;color:#111!important;font:800 11px system-ui!important;box-shadow:0 4px 18px #0004!important}
.cap-inline-hint{margin:8px 0 4px!important;padding:9px 11px!important;border:2px solid #ffd54a!important;border-radius:9px!important;background:#241f0d!important;color:#fff!important;font:700 12px/1.4 system-ui!important;max-width:520px!important}.cap-inline-hint span{margin-left:8px;color:#ffd54a!important}
.cap-attention{animation:capPulse .6s ease-in-out 3!important}@keyframes capPulse{50%{transform:scale(1.025);filter:brightness(1.18)}}
#cap-toggle{position:fixed;right:18px;bottom:18px;z-index:2147483646;background:#111;color:#fff;border:1px solid #555;border-radius:999px;padding:11px 16px;font:800 13px system-ui;cursor:pointer}
#cap-panel[hidden]{display:none!important}#cap-panel{position:fixed;right:18px;bottom:68px;z-index:2147483647;width:min(540px,calc(100vw - 24px));max-height:76vh;overflow:auto;background:#111;color:#eee;border:1px solid #444;border-radius:14px;padding:13px;box-shadow:0 18px 55px #0009;font:13px/1.45 system-ui}
#cap-panel button{background:#222;color:#eee;border:1px solid #444;border-radius:7px;padding:7px 9px;cursor:pointer}.cap-card{margin-top:8px;padding:9px;background:#181818;border:1px solid #333;border-radius:9px}.cap-small{font-size:11px;color:#aaa}.cap-ans{color:#ffd96a;font-weight:800;margin-top:5px}.cap-exp{margin-top:4px;color:#d7d7d7}.cap-row{display:flex;gap:6px;margin-top:7px;flex-wrap:wrap}.cap-on{color:#8ee59b}.cap-off{color:#ff9c9c}`;document.documentElement.appendChild(s)}
function build(){if(document.getElementById('cap-toggle'))return;style();const b=document.createElement('button');b.id='cap-toggle';b.textContent='Capitritus';document.body.appendChild(b);const p=document.createElement('section');p.id='cap-panel';p.hidden=true;p.innerHTML=`<b>Capitritus <span class="cap-small">v${V}</span></b><div class="cap-row"><button id="cap-run">Analisar agora</button><button id="cap-jump">Ir para recomendação</button><button id="cap-test">Testar IA</button><button id="cap-clear">Limpar</button></div><div id="cap-summary" class="cap-card">Inicializando…</div><div id="cap-results"></div>`;document.body.appendChild(p);b.onclick=()=>p.hidden=!p.hidden;document.getElementById('cap-run').onclick=analyze;document.getElementById('cap-jump').onclick=()=>{S.lastScroll='';scrollToRecommendation()};document.getElementById('cap-test').onclick=health;document.getElementById('cap-clear').onclick=clear}
function render(){const s=document.getElementById('cap-summary'),r=document.getElementById('cap-results');if(!s||!r)return;const found=S.items.filter(x=>x.suggestion||x.hints?.length).length,cl=S.online===true?'cap-on':S.online===false?'cap-off':'cap-small';s.innerHTML=`<div class="${cl}">${esc(S.status)}</div><div class="cap-small">Detectadas: ${S.items.length} • recomendações/pistas: ${found} • análise automática ativa</div>`;r.innerHTML='';S.items.forEach((it,n)=>{const c=document.createElement('div');c.className='cap-card';let a='';if(it.type==='open')a=it.hints?.length?`<div class="cap-ans">Pistas da IA</div>${it.hints.map(h=>`<div class="cap-exp">• ${esc(h)}</div>`).join('')}`:'<div class="cap-small">Sem pistas disponíveis.</div>';else if(it.suggestion)a=`<div class="cap-ans">Recomendação: ${esc(it.suggestion.answer||'')}</div><div class="cap-small">IA · ${Math.round((it.suggestion.confidence||0)*100)}%</div>${it.suggestion.explanation?`<div class="cap-exp">${esc(it.suggestion.explanation)}</div>`:''}`;else a='<div class="cap-small">Sem recomendação confiável.</div>';c.innerHTML=`<div class="cap-small">Item ${n+1} • ${esc(it.type)} • ${esc(it.platform)}</div><div style="font-weight:650;margin-top:4px">${esc(it.question)}</div>${a}`;r.appendChild(c)})}
function config(){const u=prompt('URL da API do Capitritus:',api());if(!u)return;GM_setValue(API_KEY,u.trim().replace(/\/+$/,''));S.cache.clear();health();analyze()}
function init(){build();setTimeout(()=>{health();analyze()},700);new MutationObserver(ms=>{if(ms.some(m=>!m.target?.closest?.('#cap-panel')&&!m.target?.closest?.('.cap-inline-hint')&&!m.target?.closest?.('.cap-badge'))){clearTimeout(S.timer);S.timer=setTimeout(analyze,1100)}}).observe(document.documentElement,{subtree:true,childList:true})}
GM_registerMenuCommand('Capitritus: analisar com IA',analyze);GM_registerMenuCommand('Capitritus: ir para recomendação',()=>{S.lastScroll='';scrollToRecommendation()});GM_registerMenuCommand('Capitritus: testar IA',health);GM_registerMenuCommand('Capitritus: configurar API',config);if(document.body)init();else addEventListener('DOMContentLoaded',init,{once:true});
})();
